// Command import-devices turns the in-game exporter's JSON into ic10go tables:
//
//   - prefabs.json -> merge into internal/builtin/prefabs.go
//   - devices.json -> internal/builtin/devicecatalog.json (embedded) + loader
//
// The exporter runs inside Stationeers (tools/ingame-exporter) and writes both
// files under Documents/My Games/Stationeers/ic10go/. Run:
//
//	go run ./tools/import-devices [prefabs.json] [devices.json] [outdir]
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const defaultOutDir = "internal/builtin"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "import-devices:", err)
		os.Exit(1)
	}
}

func run() error {
	prefabsPath, devicesPath, outDir := "", "", defaultOutDir
	args := os.Args[1:]
	if len(args) > 0 {
		prefabsPath = args[0]
	}
	if len(args) > 1 {
		devicesPath = args[1]
	}
	if len(args) > 2 {
		outDir = args[2]
	}

	if prefabsPath == "" || devicesPath == "" {
		found, err := findExports()
		if err != nil && prefabsPath == "" && devicesPath == "" {
			return err
		}
		if prefabsPath == "" {
			prefabsPath = found["prefabs.json"]
		}
		if devicesPath == "" {
			devicesPath = found["devices.json"]
		}
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if prefabsPath != "" {
		if err := importPrefabs(prefabsPath, filepath.Join(outDir, "prefabs.go")); err != nil {
			return err
		}
	}
	if devicesPath != "" {
		if err := importDevices(devicesPath, outDir); err != nil {
			return err
		}
	}
	return nil
}

// findExports looks for the exporter's files in the common user folders.
func findExports() (map[string]string, error) {
	home, _ := os.UserHomeDir()
	dirs := []string{
		filepath.Join(home, "Documents", "My Games", "Stationeers", "ic10go"),
		filepath.Join(home, "My Games", "Stationeers", "ic10go"),
		filepath.Join(home, ".local", "share", "Steam", "steamapps", "compatdata", "544550",
			"pfx", "drive_c", "users", "steamuser", "Documents", "My Games", "Stationeers", "ic10go"),
	}
	found := map[string]string{}
	for _, dir := range dirs {
		for _, name := range []string{"prefabs.json", "devices.json"} {
			if found[name] != "" {
				continue
			}
			if p := filepath.Join(dir, name); fileExists(p) {
				found[name] = p
			}
		}
	}
	if len(found) == 0 {
		return nil, fmt.Errorf("no prefabs.json/devices.json found; pass their paths as arguments")
	}
	return found, nil
}

func fileExists(p string) bool {
	info, err := os.Stat(p)
	return err == nil && !info.IsDir()
}

// -- prefabs ----------------------------------------------------------------

type prefabsFile struct {
	GameVersion string `json:"gameVersion"`
	Prefabs     []struct {
		Name        string `json:"name"`
		Hash        int64  `json:"hash"`
		DisplayName string `json:"displayName"`
	} `json:"prefabs"`
}

func importPrefabs(jsonPath, outPath string) error {
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return err
	}
	var doc prefabsFile
	if err := json.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("%s: %w", jsonPath, err)
	}
	if len(doc.Prefabs) == 0 {
		return fmt.Errorf("%s has no prefabs", jsonPath)
	}

	merged, err := readExistingPrefabs(outPath)
	if err != nil {
		return err
	}
	before := len(merged)
	for _, p := range doc.Prefabs {
		if p.Name == "" {
			continue
		}
		// Keep the English title from the localization merge; the runtime scan's
		// DisplayName follows the player's game language. Only add names the
		// localization does not carry (procedural wreckage, kits).
		if _, exists := merged[p.Name]; exists {
			continue
		}
		title := p.DisplayName
		if title == "" {
			title = p.Name
		}
		merged[p.Name] = title
	}
	if err := writePrefabs(outPath, merged); err != nil {
		return err
	}
	fmt.Printf("wrote %s: %d prefabs (was %d, added %d)\n",
		outPath, len(merged), before, len(merged)-before)
	return nil
}

var prefabLine = regexp.MustCompile(`"([^"]+)"\s*:\s*"([^"]*)"`)

func readExistingPrefabs(path string) (map[string]string, error) {
	out := map[string]string{}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, err
	}
	s := string(data)
	start := strings.Index(s, "var Prefabs")
	end := strings.Index(s, "// PrefabByHash")
	if start < 0 || end < 0 || end < start {
		return nil, fmt.Errorf("%s does not look like the prefab table", path)
	}
	for _, m := range prefabLine.FindAllStringSubmatch(s[start:end], -1) {
		out[m[1]] = m[2]
	}
	return out, nil
}

func writePrefabs(path string, prefabs map[string]string) error {
	names := make([]string, 0, len(prefabs))
	for n := range prefabs {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by tools/gengamedata / tools/import-devices from the game; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Prefabs maps a prefab name to its display title. The IC10 hash of a prefab is\n")
	b.WriteString("// Hash(name) (CRC-32).\n")
	b.WriteString("package builtin\n\n")
	b.WriteString("// Prefabs maps a prefab name to its display title.\n")
	b.WriteString("var Prefabs = map[string]string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(n), strconv.Quote(prefabs[n]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// PrefabByHash maps a prefab hash (CRC-32 of the name) back to its name.\n")
	b.WriteString("var PrefabByHash = map[uint32]string{}\n\n")
	b.WriteString("func init() {\n\tfor name := range Prefabs {\n\t\tPrefabByHash[Hash(name)] = name\n\t}\n}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format prefabs: %w", err)
	}
	return os.WriteFile(path, src, 0o644)
}

// -- devices ----------------------------------------------------------------

type devicesFile struct {
	GameVersion string       `json:"gameVersion"`
	Devices     []deviceJSON `json:"devices"`
}

type deviceJSON struct {
	PrefabName string `json:"prefabName"`
}

// devicecatalogGen is the fixed loader; the data lives in devicecatalog.json
// next to it and is embedded, so the generated Go file stays small.
const devicecatalogGen = `// Code generated by tools/import-devices; DO NOT EDIT.
package builtin

import (
	_ "embed"
	"encoding/json"
)

//go:embed devicecatalog.json
var deviceCatalogJSON []byte

func init() {
	var doc DeviceCatalogFile
	if err := json.Unmarshal(deviceCatalogJSON, &doc); err != nil {
		return
	}
	for _, d := range doc.Devices {
		if d.Name != "" {
			DeviceCatalog[d.Name] = d
		}
	}
}
`

func importDevices(jsonPath, outDir string) error {
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return err
	}
	var doc devicesFile
	if err := json.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("%s: %w", jsonPath, err)
	}

	dataOut := filepath.Join(outDir, "devicecatalog.json")
	if err := os.WriteFile(dataOut, data, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "devicecatalog_gen.go"), []byte(devicecatalogGen), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d bytes) and the loader: %d devices\n", dataOut, len(data), len(doc.Devices))
	return nil
}
