// Code generated by tools/import-devices from the game's devices.json; DO NOT EDIT.
//
// Empty until the in-game exporter has run and its JSON imported; the editor
// falls back to the whole logic-type vocabulary while it is empty.
package builtin

func init() {}
