// Code generated by tools/import-devices; DO NOT EDIT.
package builtin

import (
	_ "embed"
	"encoding/json"
)

//go:embed devicecatalog.json
var deviceCatalogJSON []byte

func init() {
	var doc DeviceCatalogFile
	if err := json.Unmarshal(deviceCatalogJSON, &doc); err != nil {
		return
	}
	for _, d := range doc.Devices {
		if d.Name != "" {
			DeviceCatalog[d.Name] = d
		}
	}
}
