// Code generated from the game instruction metadata; DO NOT EDIT.
//
// IC10Instructions maps a native IC10 mnemonic to its operand kinds and the
// in-game help text (used by the editor for .ic/.ic10 files).
package builtin

// IC10Insn is a native IC10 instruction: operand kinds (space-separated) and
// the game help text.
type IC10Insn struct {
	Sig  string
	Desc string
}

// IC10Instructions maps a native IC10 mnemonic to its signature/help.
var IC10Instructions = map[string]IC10Insn{
	"abs":    {"REGISTER VALUE", "Register = the absolute value of a"},
	"acos":   {"REGISTER VALUE", "Returns the angle (radians) whos cosine is the specified value"},
	"add":    {"REGISTER VALUE VALUE", "Register = a + b."},
	"alias":  {"NAME REGISTER_DEVICE", "Labels register or device reference with name, device references also affect what shows on the screws on the IC base."},
	"and":    {"REGISTER VALUE VALUE", "Performs a bitwise logical AND operation on the binary representation of two values. Each bit of the result is determined by evaluating the corresponding bits of the input values. If both bits are 1, the resulting bit is set to 1. Otherwise the resulting bit is set to 0."},
	"asin":   {"REGISTER VALUE", "Returns the angle (radians) whos sine is the specified value"},
	"atan":   {"REGISTER VALUE", "Returns the angle (radians) whos tan is the specified value"},
	"atan2":  {"REGISTER VALUE VALUE", "Returns the angle (radians) whose tangent is the quotient of two specified values: a (y) and b (x)"},
	"bap":    {"VALUE VALUE VALUE VALUE", "Branch to line d if abs(a - b) <= max(c * max(abs(a), abs(b)), float.epsilon * 8)"},
	"bapal":  {"VALUE VALUE VALUE VALUE", "Branch to line d if abs(a - b) <= max(c * max(abs(a), abs(b)), float.epsilon * 8) and store next line number in ra"},
	"bapz":   {"VALUE VALUE VALUE", "Branch to line c if abs(a) <= max(b * abs(a), float.epsilon * 8)"},
	"bapzal": {"VALUE VALUE VALUE", "Branch to line c if abs(a) <= max(b * abs(a), float.epsilon * 8) and store next line number in ra"},
	"bdns":   {"DEVICE VALUE", "Branch to line a if device d isn't set"},
	"bdnsal": {"DEVICE VALUE", "Jump execution to line a and store next line number if device is not set"},
	"bdse":   {"DEVICE VALUE", "Branch to line a if device d is set"},
	"bdseal": {"DEVICE VALUE", "Jump execution to line a and store next line number if device is set"},
	"beq":    {"VALUE VALUE VALUE", "Branch to line c if a == b"},
	"beqal":  {"VALUE VALUE VALUE", "Branch to line c if a == b and store next line number in ra"},
	"beqz":   {"VALUE VALUE", "Branch to line b if a == 0"},
	"beqzal": {"VALUE VALUE", "Branch to line b if a == 0 and store next line number in ra"},
	"bge":    {"VALUE VALUE VALUE", "Branch to line c if a >= b"},
	"bgeal":  {"VALUE VALUE VALUE", "Branch to line c if a >= b and store next line number in ra"},
	"bgez":   {"VALUE VALUE", "Branch to line b if a >= 0"},
	"bgezal": {"VALUE VALUE", "Branch to line b if a >= 0 and store next line number in ra"},
	"bgt":    {"VALUE VALUE VALUE", "Branch to line c if a > b"},
	"bgtal":  {"VALUE VALUE VALUE", "Branch to line c if a > b and store next line number in ra"},
	"bgtz":   {"VALUE VALUE", "Branch to line b if a > 0"},
	"bgtzal": {"VALUE VALUE", "Branch to line b if a > 0 and store next line number in ra"},
	"ble":    {"VALUE VALUE VALUE", "Branch to line c if a <= b"},
	"bleal":  {"VALUE VALUE VALUE", "Branch to line c if a <= b and store next line number in ra"},
	"blez":   {"VALUE VALUE", "Branch to line b if a <= 0"},
	"blezal": {"VALUE VALUE", "Branch to line b if a <= 0 and store next line number in ra"},
	"blt":    {"VALUE VALUE VALUE", "Branch to line c if a < b"},
	"bltal":  {"VALUE VALUE VALUE", "Branch to line c if a < b and store next line number in ra"},
	"bltz":   {"VALUE VALUE", "Branch to line b if a < 0"},
	"bltzal": {"VALUE VALUE", "Branch to line b if a < 0 and store next line number in ra"},
	"bna":    {"VALUE VALUE VALUE VALUE", "Branch to line d if abs(a - b) > max(c * max(abs(a), abs(b)), float.epsilon * 8)"},
	"bnaal":  {"VALUE VALUE VALUE VALUE", "Branch to line d if abs(a - b) <= max(c * max(abs(a), abs(b)), float.epsilon * 8) and store next line number in ra"},
	"bnan":   {"VALUE VALUE", "Branch to line b if a is not a number (NaN)"},
	"bnaz":   {"VALUE VALUE VALUE", "Branch to line c if abs(a) > max (b * abs(a), float.epsilon * 8)"},
	"bnazal": {"VALUE VALUE VALUE", "Branch to line c if abs(a) > max (b * abs(a), float.epsilon * 8) and store next line number in ra"},
	"bne":    {"VALUE VALUE VALUE", "Branch to line c if a != b"},
	"bneal":  {"VALUE VALUE VALUE", "Branch to line c if a != b and store next line number in ra"},
	"bnez":   {"VALUE VALUE", "branch to line b if a != 0"},
	"bnezal": {"VALUE VALUE", "Branch to line b if a != 0 and store next line number in ra"},
	"brap":   {"VALUE VALUE VALUE VALUE", "Relative branch to line d if abs(a - b) <= max(c * max(abs(a), abs(b)), float.epsilon * 8)"},
	"brapz":  {"VALUE VALUE VALUE", "Relative branch to line c if abs(a) <= max(b * abs(a), float.epsilon * 8)"},
	"brdns":  {"DEVICE VALUE", "Relative jump to line a if device is not set"},
	"brdse":  {"DEVICE VALUE", "Relative jump to line a if device is set"},
	"breq":   {"VALUE VALUE VALUE", "Relative branch to line c if a == b"},
	"breqz":  {"VALUE VALUE", "Relative branch to line b if a == 0"},
	"brge":   {"VALUE VALUE VALUE", "Relative jump to line c if a >= b"},
	"brgez":  {"VALUE VALUE", "Relative branch to line b if a >= 0"},
	"brgt":   {"VALUE VALUE VALUE", "relative jump to line c if a > b"},
	"brgtz":  {"VALUE VALUE", "Relative branch to line b if a > 0"},
	"brle":   {"VALUE VALUE VALUE", "Relative jump to line c if a <= b"},
	"brlez":  {"VALUE VALUE", "Relative branch to line b if a <= 0"},
	"brlt":   {"VALUE VALUE VALUE", "Relative jump to line c if a < b"},
	"brltz":  {"VALUE VALUE", "Relative branch to line b if a < 0"},
	"brna":   {"VALUE VALUE VALUE VALUE", "Relative branch to line d if abs(a - b) > max(c * max(abs(a), abs(b)), float.epsilon * 8)"},
	"brnan":  {"VALUE VALUE", "Relative branch to line b if a is not a number (NaN)"},
	"brnaz":  {"VALUE VALUE VALUE", "Relative branch to line c if abs(a) > max(b * abs(a), float.epsilon * 8)"},
	"brne":   {"VALUE VALUE VALUE", "Relative branch to line c if a != b"},
	"brnez":  {"VALUE VALUE", "Relative branch to line b if a != 0"},
	"ceil":   {"REGISTER VALUE", "Register = smallest integer greater than a"},
	"cos":    {"REGISTER VALUE", "Returns the cosine of the specified angle (radians)"},
	"define": {"NAME NUMBER", "Creates a label that will be replaced throughout the program with the provided value."},
	"div":    {"REGISTER VALUE VALUE", "Register = a / b"},
	"exp":    {"REGISTER VALUE", "Register = exp(a) or e^a"},
	"floor":  {"REGISTER VALUE", "Register = largest integer less than a"},
	"get":    {"REGISTER DEVICE ADDRESS", ""},
	"getd":   {"REGISTER DEVICE_ID ADDRESS", ""},
	"hcf":    {"", "Halt and catch fire"},
	"j":      {"VALUE", "Jump execution to line a"},
	"jal":    {"VALUE", "Jump execution to line a and store next line number in ra"},
	"jr":     {"VALUE", "Relative jump to line a"},
	"l":      {"REGISTER DEVICE LOGIC_TYPE", "Loads device LogicType to register by housing index value."},
	"label":  {"", "DEPRECATED"},
	"lb":     {"REGISTER DEVICE_TYPE LOGIC_TYPE BATCH_MODE", "Loads LogicType from all output network devices with provided type hash using the provide batch mode. Average (0), Sum (1), Minimum (2), Maximum (3). Can use either the word, or the number."},
	"lbn":    {"REGISTER DEVICE_TYPE DEVICE_NAME LOGIC_TYPE BATCH_MODE", "Loads LogicType from all output network devices with provided type and name hashes using the provide batch mode. Average (0), Sum (1), Minimum (2), Maximum (3). Can use either the word, or the number."},
	"lbns":   {"REGISTER DEVICE_TYPE DEVICE_NAME INDEX SLOT_LOGIC_TYPE BATCH_MODE", "Loads LogicSlotType from slotIndex from all output network devices with provided type and name hashes using the provide batch mode. Average (0), Sum (1), Minimum (2), Maximum (3). Can use either the word, or the number."},
	"lbs":    {"REGISTER DEVICE_TYPE INDEX SLOT_LOGIC_TYPE BATCH_MODE", "Loads LogicSlotType from slotIndex from all output network devices with provided type hash using the provide batch mode. Average (0), Sum (1), Minimum (2), Maximum (3). Can use either the word, or the number."},
	"ld":     {"REGISTER DEVICE_ID LOGIC_TYPE", "Loads device LogicType to register by direct ID reference."},
	"log":    {"REGISTER VALUE", "Register = base e log(a) or ln(a)"},
	"lr":     {"REGISTER DEVICE REAGENT_MODE VALUE", "Loads reagent of device's ReagentMode where a hash of the reagent type to check for. ReagentMode can be either Contents (0), Required (1), Recipe (2). Can use either the word, or the number."},
	"ls":     {"REGISTER DEVICE VALUE SLOT_LOGIC_TYPE", "Loads slot LogicSlotType on device to register."},
	"max":    {"REGISTER VALUE VALUE", "Register = max of a or b"},
	"min":    {"REGISTER VALUE VALUE", "Register = min of a or b"},
	"mod":    {"REGISTER VALUE VALUE", "Register = a mod b (note: NOT a % b)"},
	"move":   {"REGISTER VALUE", "Register = provided num or register value."},
	"mul":    {"REGISTER VALUE VALUE", "Register = a * b"},
	"nor":    {"REGISTER VALUE VALUE", "Performs a bitwise logical NOR (NOT OR) operation on the binary representation of two values. Each bit of the result is determined by evaluating the corresponding bits of the input values. If both bits are 0, the resulting bit is set to 1. Otherwise, if at least one bit is 1, the resulting bit is set to 0."},
	"not":    {"REGISTER VALUE", "Performs a bitwise logical NOT operation flipping each bit of the input value, resulting in a binary complement. If a bit is 1, it becomes 0, and if a bit is 0, it becomes 1."},
	"or":     {"REGISTER VALUE VALUE", "Performs a bitwise logical OR operation on the binary representation of two values. Each bit of the result is determined by evaluating the corresponding bits of the input values. If either bit is 1, the resulting bit is set to 1. If both bits are 0, the resulting bit is set to 0."},
	"peek":   {"REGISTER", "Register = the value at the top of the stack"},
	"poke":   {"ADDRESS VALUE", ""},
	"pop":    {"REGISTER", "Register = the value at the top of the stack and decrements sp"},
	"push":   {"VALUE", "Pushes the value of a to the stack at sp and increments sp"},
	"put":    {"DEVICE ADDRESS VALUE", ""},
	"putd":   {"DEVICE_ID ADDRESS VALUE", ""},
	"rand":   {"REGISTER", "Register = a random value x with 0 <= x < 1"},
	"round":  {"REGISTER VALUE", "Register = a rounded to nearest integer"},
	"s":      {"DEVICE LOGIC_TYPE VALUE", "Stores register value to LogicType on device by housing index value."},
	"sap":    {"REGISTER VALUE VALUE VALUE", "Register = 1 if abs(a - b) <= max(c * max(abs(a), abs(b)), float.epsilon * 8), otherwise 0"},
	"sapz":   {"REGISTER VALUE VALUE", "Register = 1 if abs(a) <= max(b * abs(a), float.epsilon * 8), otherwise 0"},
	"sb":     {"DEVICE_TYPE LOGIC_TYPE VALUE", "Stores register value to LogicType on all output network devices with provided type hash."},
	"sbn":    {"DEVICE_TYPE DEVICE_NAME LOGIC_TYPE VALUE", "Stores register value to LogicType on all output network devices with provided type hash and name."},
	"sbs":    {"DEVICE_TYPE INDEX SLOT_LOGIC_TYPE VALUE", "Stores register value to LogicSlotType on all output network devices with provided type hash in the provided slot."},
	"sd":     {"DEVICE_ID LOGIC_TYPE VALUE", "Stores register value to LogicType on device by direct ID reference."},
	"sdns":   {"REGISTER DEVICE", "Register = 1 if device is not set, otherwise 0"},
	"sdse":   {"REGISTER DEVICE", "Register = 1 if device is set, otherwise 0."},
	"select": {"REGISTER VALUE VALUE VALUE", "Register = b if a is non-zero, otherwise c"},
	"seq":    {"REGISTER VALUE VALUE", "Register = 1 if a == b, otherwise 0"},
	"seqz":   {"REGISTER VALUE", "Register = 1 if a == 0, otherwise 0"},
	"sge":    {"REGISTER VALUE VALUE", "Register = 1 if a >= b, otherwise 0"},
	"sgez":   {"REGISTER VALUE", "Register = 1 if a >= 0, otherwise 0"},
	"sgt":    {"REGISTER VALUE VALUE", "Register = 1 if a > b, otherwise 0"},
	"sgtz":   {"REGISTER VALUE", "Register = 1 if a > 0, otherwise 0"},
	"sin":    {"REGISTER VALUE", "Returns the sine of the specified angle (radians)"},
	"sla":    {"REGISTER VALUE VALUE", "Performs a bitwise arithmetic left shift operation on the binary representation of a value. It shifts the bits to the left and fills the vacated rightmost bits with a copy of the sign bit (the most significant bit)."},
	"sle":    {"REGISTER VALUE VALUE", "Register = 1 if a <= b, otherwise 0"},
	"sleep":  {"VALUE", "Pauses execution on the IC for a seconds"},
	"slez":   {"REGISTER VALUE", "Register = 1 if a <= 0, otherwise 0"},
	"sll":    {"REGISTER VALUE VALUE", "Performs a bitwise logical left shift operation on the binary representation of a value. It shifts the bits to the left and fills the vacated rightmost bits with zeros."},
	"slt":    {"REGISTER VALUE VALUE", "Register = 1 if a < b, otherwise 0"},
	"sltz":   {"REGISTER VALUE", "Register = 1 if a < 0, otherwise 0"},
	"sna":    {"REGISTER VALUE VALUE VALUE", "Register = 1 if abs(a - b) > max(c * max(abs(a), abs(b)), float.epsilon * 8), otherwise 0"},
	"snan":   {"REGISTER VALUE", "Register = 1 if a is NaN, otherwise 0"},
	"snanz":  {"REGISTER VALUE", "Register = 0 if a is NaN, otherwise 1"},
	"snaz":   {"REGISTER VALUE VALUE", "Register = 1 if abs(a) > max(b * abs(a), float.epsilon), otherwise 0"},
	"sne":    {"REGISTER VALUE VALUE", "Register = 1 if a != b, otherwise 0"},
	"snez":   {"REGISTER VALUE", "Register = 1 if a != 0, otherwise 0"},
	"sqrt":   {"REGISTER VALUE", "Register = square root of a"},
	"sra":    {"REGISTER VALUE VALUE", "Performs a bitwise arithmetic right shift operation on the binary representation of a value. It shifts the bits to the right and fills the vacated leftmost bits with a copy of the sign bit (the most significant bit)."},
	"srl":    {"REGISTER VALUE VALUE", "Performs a bitwise logical right shift operation on the binary representation of a value. It shifts the bits to the right and fills the vacated leftmost bits with zeros"},
	"ss":     {"DEVICE VALUE SLOT_LOGIC_TYPE REGISTER", "Stores register value to device stored in a slot LogicSlotType on device."},
	"sub":    {"REGISTER VALUE VALUE", "Register = a - b."},
	"tan":    {"REGISTER VALUE", "Returns the tan of the specified angle (radians) "},
	"trunc":  {"REGISTER VALUE", "Register = a with fractional part removed"},
	"xor":    {"REGISTER VALUE VALUE", "Performs a bitwise logical XOR (exclusive OR) operation on the binary representation of two values. Each bit of the result is determined by evaluating the corresponding bits of the input values. If the bits are different (one bit is 0 and the other is 1), the resulting bit is set to 1. If the bits are the same (both 0 or both 1), the resulting bit is set to 0."},
	"yield":  {"", "Pauses execution for 1 tick"},
}
